services:
  backend:
    restart: on-failure
    image: backend_server
    build: .
    env_file: ./.env
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      SPRING_APPLICATION_JSON: '{     
        "spring.datasource.url" : "$POSTGRES_URL",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "validate",
        "spring.jpa.generate-ddl" : "true",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.open-in-view" : "false",
        "spring.liquibase.drop-first" : "false"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
